[[pages]]
path = "app.py"
name = "ODTP"
icon = "ğŸŒ"

[[pages]]
path = "users.py"
name = "Users"
icon = "ğŸŒ"

[[pages]]
path = "digitaltwins.py"
name = "Digital Twins"
icon = "ğŸŒ"

[[pages]]
path = "components.py"
name = "Components"
icon = "ğŸŒ"

[[pages]]
path = "workflow.py"
name = "Workflow Designer"
icon = "ğŸŒ"

[[pages]]
path = "logs.py"
name = "Logs"
icon = "ğŸŒ"

[[pages]]
path = "snapshots.py"
name = "Snapshots"
icon = "ğŸŒ"

[[pages]]
path = "semantics.py"
name = "Semantics"
icon = "ğŸŒ"


[[pages]]
path = "init.py"
name = "Init"
icon = "ğŸŒ"


