[[pages]]
path = "gui/app.py"
name = "ODTP"
icon = "ğŸŒ"

[[pages]]
path = "gui/users.py"
name = "Users"
icon = "ğŸŒ"

[[pages]]
path = "gui/runs.py"
name = "Run component"
icon = "ğŸŒ"

[[pages]]
path = "gui/workflow.py"
name = "Workflow Designer"
icon = "ğŸŒ"

[[pages]]
path = "gui/digitaltwins.py"
name = "Digital Twins"
icon = "ğŸŒ"

[[pages]]
path = "gui/logs.py"
name = "Logs"
icon = "ğŸŒ"

[[pages]]
path = "gui/results.py"
name = "Results"
icon = "ğŸŒ"

[[pages]]
path = "gui/semantics.py"
name = "Semantics"
icon = "ğŸŒ"

[[pages]]
path = "gui/datavis.py"
name = "Data Visualization"
icon = "ğŸŒ"

[[pages]]
path = "gui/servinit.py"
name = "Services Configuration"
icon = "ğŸŒ"


